### ISSUE TITLE
Inconsistent branding 

### ISSUE THREAD

**Issue by ghost** [Diego-Ivan/Paper-Clip#14]
Hi, there are two case of "PDF Metadata Editor" usage

https://github.com/Diego-Ivan/Paper-Clip/blob/main/src/meson.build#L26
https://github.com/Diego-Ivan/Paper-Clip/blob/main/src/window.ui#L162

And 9 case of Paper Clip usage.

https://github.com/Diego-Ivan/Paper-Clip/blob/main/README.md?plain=1#L3
https://github.com/Diego-Ivan/Paper-Clip/blob/main/README.md?plain=1#L33
https://github.com/Diego-Ivan/Paper-Clip/blob/main/README.md?plain=1#L37
https://github.com/Diego-Ivan/Paper-Clip/blob/main/README.md?plain=1#L41
https://github.com/Diego-Ivan/Paper-Clip/blob/main/data/io.github.diegoivan.pdf_metadata_editor.appdata.xml.in#L7
https://github.com/Diego-Ivan/Paper-Clip/blob/main/data/io.github.diegoivan.pdf_metadata_editor.desktop.in#L2
https://github.com/Diego-Ivan/Paper-Clip/blob/main/pdf-metadata-editor.doap#L8
https://github.com/Diego-Ivan/Paper-Clip/blob/main/src/application.vala#L53
https://github.com/Diego-Ivan/Paper-Clip/blob/main/src/window.ui#L10

IMHO, you may choice one of them and focus on it.

**Comment by Diego-Ivan** [comment]
Thank you for your report! Paper Clip is the official name, currently this papercuts have been fixed in MR #12

**Comment by ghost** [comment]
Thanks a lot :+1:
