### ISSUE TITLE
Suggestion: "open with [Paper Clip]" option

### ISSUE THREAD

**Issue by rene-coty** [Diego-Ivan/Paper-Clip#22]
At present, it's not possible to edit PDF metadata by opening it with the application directly: the application must first be opened and the file dropped into it / opened from the interface.
It would be a useful time-saver to have the option "Open file with [Paper Clip]" directly from the file manager..

**Comment by Diego-Ivan** [comment]
Thanks for the suggestion! It is now implemented and will be available in the next release :smile:
