### ISSUE TITLE
feature: Add support to edit PDF/A (1.4-1.6) XMP metadata

### ISSUE THREAD

**Issue by narcisgarcia** [Diego-Ivan/Paper-Clip#37]
I've exported a document with LibreOffice and selected PDF/A mode (ISO). It generates PDF version 1.6 file.
Then used Paper Clip (v3.2) and metadata edits aren't reflected on some PDF viewers (such as Evince).

**Comment by Diego-Ivan** [comment]
I have made a couple of tests using the latest version (v3.5) with PDF/A and LibreOffice Writer and in all cases the metadata is edited and reflected in Evince. Could you provide more details? For instance, which version of LibreOffice you used, which options you enabled to export to, so I can see if I can replicate the issue myself.

**Comment by narcisgarcia** [comment]
LibreOffice DRAW: 7.4.5.1
Paper-clip package origin: dl.flathub.org

I put a bitmap to fill (and more) one page. Then I export to PDF.
"Creation software" and "Conversion software" are not saved. Paper-clip thinks yes.


Note: Drag & drop file from folder to app does not work. I must use "Open" button.

**Comment by narcisgarcia** [comment]
Now I've updated to Paper Clip 3.5 and find same behavior for LO Draw exported PDFs.

**Comment by Diego-Ivan** [comment]
I have managed to replicate the issue, and seems to be PDF/A documents and support for their metadata within Paper Clip's underlying library ([Libpoppler](https://gitlab.freedesktop.org/poppler/poppler/-/issues/14)). I will try adding support for PDF versions, but it will likely will not be soon.

> Note: Drag & drop file from folder to app does not work. I must use "Open" button.

Thanks for letting me now! I will look into it and will fix it as soon as possible.

**Comment by Diego-Ivan** [comment]
@narcisgarcia Hello there. This week I worked in solving this issue and it's now merged in main. If you want to test it before the next release, you can run it using GNOME Builder or manually building. In the case you do not want to download Builder or compiling it by yourself, let me know and I will provide you a `.flatpak` file so you can test it without building anything.

**Comment by narcisgarcia** [comment]
AppImage can be easier for me to avoid build and/or environments complication.
