### ISSUE TITLE
TOC editing

### ISSUE THREAD

**Issue by astrosticks** [Diego-Ivan/Paper-Clip#42]
Would editing the table of contents of a PDF fall into the scope of this project? There don't seem to be any easy tools for this that are ported for modern Linux desktop.

**Comment by Diego-Ivan** [comment]
Hello there! Sorry for replying to this issue a little bit late, just saw it in my email. While I think that having such tool would be great, I think it does fall out of the scope of Paper Clip. However, you can open an issue on [this repository](https://gitlab.gnome.org/bertob/app-ideas) to suggest it, and hopefully, someone interested in working in such app can pick it up :)
