### ISSUE TITLE
Hit return to add a tag

### ISSUE THREAD

**Issue by xplosionmind** [Diego-Ivan/Paper-Clip#44]
While adding tags to a specific PDF, it is quite frustrating to have to click on the “+” with the mouse to add a new tag, rather than simply pressing the return button.

**Comment by Diego-Ivan** [comment]
This feature seems so essential that I almost thought this was already in. Thanks for the feedback!

`<Ctrl>Return` to add a new keyword was planned but I wonder why I never implemented it. This will make it to the next release
