### ISSUE TITLE
App icon improvements

### ISSUE THREAD

**Issue by bragefuglseth** [Diego-Ivan/Paper-Clip#6]
Hi! I'm from the GNOME App Icon Design group. 😃 I'm here because you have requested inclusion in GNOME Circle for PDF Metadata Editor. A reviewer asked for help with icon design for a couple of apps, yours included.

The current icon follows the GNOME guidelines, which is great! However, it has some room for improvement:

- The lines on the document could be spaced evenly
- The "chin" on the sheet could be styled to make it look like an actual stack of paper sheets
- The metaphor itself is a little unclear, as the app isn't really for editing PDF documents directly, but rather editing their *metadata*
- There are some weird quirks with the pencil
<img src="https://user-images.githubusercontent.com/91388039/220094237-c7f52e24-60cf-4e21-913a-6e4d66225588.png" height="300px"/>

- The icon elements should be aligned with the pixel grid, which will make it look sharp even at small sizes (you can show the grid by pressing `shift + 3` in Inkscape) 
<img src="https://user-images.githubusercontent.com/91388039/220092750-54fcd327-9d89-433f-9a51-cd6eae4c25c2.png" height="600px"/>

Based on these points, I have some improvements I'd like to make to the icon:

- Redesign the icon from the ground up to make the elements be properly spaced and aligned to the pixel grid
- Change the metaphor to clarify what the app does. I'd like to try a smaller sheet of paper paperclipped to the document, with the pencil writing on that instead.

In addition to this, I have a suggestion regarding the name of the app, as the current one is very generic. The new icon metaphor would allow for the name "Paper Clip", which is more distinct than the current name, and more in line with the names of other third-party GNOME apps. The use case of the app could be signified through the app description anyways ("Edit the metadata of PDF documents").

I'll start designing now, and open a merge request when I'm done. If you want to do this yourself, feel free to interrupt me / close the merge request. If you have any further questions about this icon / icon design in general, you can join the [GNOME App Icon Design chat room](https://matrix.to/#/#appicondesign:gnome.org) on Matrix. :smile:

**Comment by Diego-Ivan** [comment]
Hello there, thanks for your feedback!

> The metaphor itself is a little unclear, as the app isn't really for editing PDF documents directly, but rather editing their metadata

Yes, that's definitely a problem, the icon doesn't really reflect editing metadata, and might be a little confusing.

> Change the metaphor to clarify what the app does. I'd like to try a smaller sheet of paper paperclipped to the document, with the pencil writing on that instead.

Sounds good to me! I think the name *Paper Clip* is also great, given that the current name is very generic and a change would be great for it.

Thank you so much for your feedback and work! :)

**Comment by bragefuglseth** [comment]
Great! I'm working on the icon, will add it into the appropriate places and open a PR as soon as it's ready.
