### ISSUE TITLE
XMP Dublin Core namespace - Document Title dc:title

### ISSUE THREAD

**Issue by langfingaz** [Diego-Ivan/Paper-Clip#67]
If a PDF has the XMP tag `dc:title=Foo`, then Firefox (on Windows and Linux) as well as the GNOME Document Viewer/Evince (on Linux) have "Foo" as window title.

It would be great if Paper Clip would display and allow editing of this value.

---

Documentation about the XMP Dublin Core namespace:
- https://developer.adobe.com/xmp/docs/XMPNamespaces/dc/
- https://exiftool.org/TagNames/XMP.html (In section XMP dc Tags)

---

One can also set this value with `exiftool`:

```shell
exiftool -xmp-dc:title="Foo" document.pdf
```

Screenshot of Firefox:

![Screenshot from 2024-01-22 14-52-02](https://github.com/Diego-Ivan/Paper-Clip/assets/10504672/41ea063c-a08c-4888-a2c3-d8ffd136ecd3)

Screenshot of Evince:

![Screenshot from 2024-01-22 14-50-56](https://github.com/Diego-Ivan/Paper-Clip/assets/10504672/c5d40feb-7f37-432f-8b79-656236c62a9c)

**Comment by langfingaz** [comment]
As dc:title is not a PDF metadata, but rather file metadata in general, I would understand if this is out of scope for this project. Nevertheless, I think that it would be useful for many users of Paper Clip.

By the way: Paper Clip is already really great as is! Many thanks for developing it :+1: and with `exiftool` there exists already a workaround.

**Comment by Diego-Ivan** [comment]
Thanks! It is indeed within the scope of the project; I think it makes sense to keep the DublinCore metadata in sync with the other ones. Will implement this for the next release :)

**Comment by omentic** [comment]
Hello, I am running v5.5, and I have noticed the Dublin Core metadata is still not in sync with the ordinary metadata.

**Comment by Diego-Ivan** [comment]
Could you provide an example where this is the case? It will help us debug the issue further :)
