### ISSUE TITLE
update croatian and german translation files

### ISSUE THREAD

**Issue by milotype** [Diego-Ivan/Paper-Clip#73]
Please add attached updated Croatian and German `.po` translation files.
- Both files are updated according to the current `pdf-metadata-editor.pot` file (POT-Creation-Date: 2024-01-27 21:42-0600).
- All unused/old strings are deleted

Due to my old MacOS and Firefox versions I'm not able to send merge requests via GitHub :-((
[hr-de.zip](https://github.com/Diego-Ivan/Paper-Clip/files/14363001/hr-de.zip)

**Comment by Diego-Ivan** [comment]
Sorry I missed this, will add them now :)
