### ISSUE TITLE
Add Hindi translation

### ISSUE THREAD

**Issue by Scrambled777** [Diego-Ivan/Paper-Clip#79]
@Diego-Ivan Could you assist me in adding Hindi translation to this project. I don't have knowledge to open merge request.

I have uploaded  it as a zip file here. 
[Paper Clip.zip](https://github.com/Diego-Ivan/Paper-Clip/files/14773793/Paper.Clip.zip)

Will really appreciate your help.

**Comment by Diego-Ivan** [comment]
Just merged into main. Thanks for your contribution!
