### ISSUE TITLE
Unable to open files Input/output error

### ISSUE THREAD

**Issue by diazbastian** [Diego-Ivan/Paper-Clip#93]
I've been using Paper Clip for a while now, however, today I noticed that I can't open any type of PDF files in my HOME directory. When I run Paper Clip from the terminal I just get an error:

`(pdf-metadata-editor:2): Paper Clip-CRITICAL **: 22:40:05.842: window.vala:184: Error splicing file: Input/output error`

I tested different PDF documents, even some I had previously edited. I don't know how to get more log information through flatpak.

OS: Fedora Workstation  bit
Desktop: GNOME 46 Wayland

Paper Clip 5.5
Libraries:
Gtk 4.14.4 (Runtime)
Libadwaita: 1.5.0 (Compile Time)
Poppler: 23.01.0 (Compile Time)
Exempi: 2.6.4 (Compile Time)
GdkPixbuf 2.42.10 (Compile Time)

Running under Flatpak? true (version 1.15.8)
OS Information? GNOME 46 (Flatpak runtime)

**Comment by Diego-Ivan** [comment]
I had never seen this error before. Does this happen with all of the documents in your HOME directory, or just with some of them?

**Comment by diazbastian** [comment]
This happens to all documents in the HOME directory. I've tried several documents, even some I edited with Paper Clip  the night before, but I can't open any PDF documents.

A small screencast


https://github.com/user-attachments/assets/93324188-2889-49e8-b7b3-17e5e48b1ebc

**Comment by Diego-Ivan** [comment]
Does this happen only with Paper Clip? Or does this happen with other apps (especially running under Flatpak)?

**Comment by diazbastian** [comment]
> Does this happen only with Paper Clip? Or does this happen with other apps (especially running under Flatpak)?

So far I'm only having problems with Paper Clip. Even though I'm using the standard version of fedora (non-silverblue), most of the apps I use come from flathub. I installed an app from flathub called "PDF metadata editor" and it does the job.

This is interesting to me, as I've tried previous versions of Paper Clip using WareHouse app and the problem persists. The issue is probably very specific, but I don't recall doing anything special with this or other apps.

**Comment by xplosionmind** [comment]
Hi! I was about to open an issue about this myself. It has never happened to me before, it’s happening now for the first time (I haven’t been using Paper Clip for a couple of weeks).

```
flatpak run io.github.diegoivan.pdf_metadata_editor 

(pdf-metadata-editor:2): Paper Clip-CRITICAL **: 10:30:29.611: window.vala:184: Error splicing file: Input/output error
```

```
neofetch                        
             .',;::::;,'.                tommi@tfw 
         .';:cccccccccccc:;,.            --------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 40 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: Laptop 13 (AMD Ryzen 7040Series) A7 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.10.3-200.fc40.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 3 hours, 40 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2323 (rpm), 127 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.9 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 2256x1504 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 46.4 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: kgx 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: AMD Ryzen 7 7840U w/ Radeon 780M Graphics (16) @ 5.132GHz 
:cccccccccccccccccccccccccccc:'.         GPU: AMD ATI c1:00.0 Phoenix1 
.:cccccccccccccccccccccc:;,..            Memory: 5129MiB / 27858MiB 
  '::cccccccccccccc::;,.
```

**Comment by Diego-Ivan** [comment]
@diazbastian @xplosionmind Thanks for reporting this issue, I have made a fix in branch https://github.com/Diego-Ivan/Paper-Clip/tree/fix-io-error, please test it if you are able to give it a try. In case you need a compiled Flatpak, please let me know so I can provide it to you.

**Comment by xplosionmind** [comment]
Thanks so much, @Diego-Ivan! I would really appreciate a Flatpak package because I use that, and I am terrible with other installation solutions 🤯

**Comment by Diego-Ivan** [comment]
Sure, there is a .flatpak available in https://github.com/Diego-Ivan/Paper-Clip/releases/tag/v5.5-test. Once downloaded, clicking on it should open your software store and allow you to install it from there.

**Comment by Diego-Ivan** [comment]
An update is just being published to Flathub, so you will receive an update in a few hours, thanks for reporting this issue!

**Comment by diazbastian** [comment]
Thank you very much, it works perfectly.
